name: Task1 eval

on: [push]

jobs:
  Task1-eval-full:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install task1 package
        run: |
          pip install -e task1/
      - name: Task1 full evaluation
        run: |
          pytest --pyargs a4_course_cvdl_t1
  Task1-eval-failfast:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install task1 package
        run: |
          pip install -e task1/
      - name: Task1 failfast evaluation
        run: |
          pytest --pyargs a4_course_cvdl_t1 -x
